name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Copy version files
        shell: bash
        run: |
          cp curl/src/main/native/config/versions/nghttp2ver.h curl/src/main/native/nghttp2/lib/includes/nghttp2/nghttp2ver.h
          cp curl/src/main/native/config/versions/nghttp3ver.h curl/src/main/native/nghttp3/lib/includes/nghttp3/version.h
          cp curl/src/main/native/config/versions/ngtcp2ver.h curl/src/main/native/ngtcp2/lib/includes/ngtcp2/version.h
          echo "#include \"tool_hugehelp.h\"" > curl/src/main/native/curl/src/tool_hugehelp.c
      - name: Build with Gradle
        run: |
          ./gradlew :e:assembleRelease
          ./gradlew publishToMavenLocal
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-app
          path: example/build/outputs
      - name: Upload library
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-library
          path: ~/.m2
